# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-alloy-db
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: terraform-google-alloy-db
  source:
    repo: https://github.com/anaik91/terraform-google-alloy-db.git
    sourceType: git
  version: 0.0.1
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  icon: assets/icon.png
  examples:
  - name: example_with_multiple_readpool
    location: examples/example_with_multiple_readpool
  - name: example_with_primary_instance
    location: examples/example_with_primary_instance
  - name: example_with_readpool_instances
    location: examples/example_with_readpool_instances
  - name: simple_example
    location: examples/simple_example
  variables:
  - name: automated_backup_policy
    description: The automated backup policy for this cluster.
    type: |-
      object({
          location      = optional(string),
          backup_window = optional(string),
          enabled       = optional(bool),
          weekly_schedule = object({
            days_of_week = optional(list(string)),
            start_times  = list(string),
          }),
          quantity_based_retention_count = optional(number),
          time_based_retention_count     = optional(string),
          labels                         = optional(map(string))
        })
    default:
      backup_window: 1800s
      enabled: false
      labels:
        test: alloydb-cluster
      location: us-central1
      quantity_based_retention_count: 1
      time_based_retention_count: "null"
      weekly_schedule:
        days_of_week:
        - FRIDAY
        start_times:
        - "2:00:00:00"
    required: false
  - name: cluster_display_name
    description: Display Name for Alloy DB Cluster
    type: string
    default: ""
    required: false
  - name: cluster_id
    description: Configuration of the AlloyDb cluster.
    type: string
    required: true
  - name: cluster_initial_user
    description: Alloy DB Cluster Initial User Credentials
    type: |-
      object({
          user     = optional(string),
          password = string
        })
    default:
      password: alloydb-cluster-full
      user: alloydb-cluster-full
    required: false
  - name: cluster_labels
    description: Labels to identify the Alloy DB Cluster
    type: map(string)
    default: {}
    required: false
  - name: cluster_location
    description: Location where AlloyDb cluster will be deployed.
    type: string
    default: us-central1
    required: false
  - name: network_self_link
    description: Network ID where the AlloyDb cluster will be deployed.
    type: string
    required: true
  - name: primary_instance
    description: Primary cluster configuration that supports read and write operations.
    type: |-
      object({
          instance_id       = string,
          instance_type     = string,
          machine_cpu_count = number,
          display_name      = string,
          database_flags    = map(string)
        })
    required: true
  - name: project_id
    description: The ID of the project in which to provision resources.
    type: string
    required: true
  - name: read_pool_instance
    description: List of Read Pool Instances to be created
    type: |-
      list(object({
          instance_id       = string,
          display_name      = string,
          instance_type     = string,
          node_count        = number,
          database_flags    = map(string),
          availability_type = string,
          ZONE              = string,
          machine_cpu_count = number
        }))
    default: []
    required: false
  outputs:
  - name: cluster_id
    description: ID of the Alloy DB Cluster created
  - name: primary_instance_id
    description: ID of the primary instance created
  - name: read_instance_ids
    description: IDs of the read instances created
  roles:
  - level: Project
    roles:
    - roles/owner
  services:
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - servicenetworking.googleapis.com
  - alloydb.googleapis.com
